#include "legokeymaps.h"

#include <SDL3/SDL_scancode.h>

KeyMaps g_keyMaps = {
	{SDL_SCANCODE_UP, SDL_SCANCODE_KP_8},
	{SDL_SCANCODE_DOWN, SDL_SCANCODE_KP_2},
	{SDL_SCANCODE_LEFT, SDL_SCANCODE_KP_4},
	{SDL_SCANCODE_RIGHT, SDL_SCANCODE_KP_6},
	{SDL_SCANCODE_LCTRL, SDL_SCANCODE_RCTRL}
};
