name = "isle-relay"
main = "relay.ts"
compatibility_date = "2024-01-01"
workers_dev = false
preview_urls = false

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" },
  { name = "ROOM_REGISTRY", class_name = "RoomRegistry" }
]

[vars]
MAX_PLAYERS_CEILING = 64

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_classes = ["RoomRegistry"]
