services:
  app:
    image: ghcr.io/isledecomp/isle-portable-emscripten:master
    ports:
      - "6931:6931"
    volumes:
      - ${ASSETS_PATH}:/assets

  caddy:
    image: caddy:latest
    ports:
      - "6932:6932"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data: