#pragma once

#include "mortar_begin.h"

#include <stdint.h>

typedef uint32_t MORTAR_Keycode;

#define MORTARK_UNKNOWN 0x00000000u            /**< 0 */
#define MORTARK_RETURN 0x0000000du             /**< '\r' */
#define MORTARK_ESCAPE 0x0000001bu             /**< '\x1B' */
#define MORTARK_BACKSPACE 0x00000008u          /**< '\b' */
#define MORTARK_TAB 0x00000009u                /**< '\t' */
#define MORTARK_SPACE 0x00000020u              /**< ' ' */
#define MORTARK_EXCLAIM 0x00000021u            /**< '!' */
#define MORTARK_DBLAPOSTROPHE 0x00000022u      /**< '"' */
#define MORTARK_HASH 0x00000023u               /**< '#' */
#define MORTARK_DOLLAR 0x00000024u             /**< '$' */
#define MORTARK_PERCENT 0x00000025u            /**< '%' */
#define MORTARK_AMPERSAND 0x00000026u          /**< '&' */
#define MORTARK_APOSTROPHE 0x00000027u         /**< '\'' */
#define MORTARK_LEFTPAREN 0x00000028u          /**< '(' */
#define MORTARK_RIGHTPAREN 0x00000029u         /**< ')' */
#define MORTARK_ASTERISK 0x0000002au           /**< '*' */
#define MORTARK_PLUS 0x0000002bu               /**< '+' */
#define MORTARK_COMMA 0x0000002cu              /**< ',' */
#define MORTARK_MINUS 0x0000002du              /**< '-' */
#define MORTARK_PERIOD 0x0000002eu             /**< '.' */
#define MORTARK_SLASH 0x0000002fu              /**< '/' */
#define MORTARK_0 0x00000030u                  /**< '0' */
#define MORTARK_1 0x00000031u                  /**< '1' */
#define MORTARK_2 0x00000032u                  /**< '2' */
#define MORTARK_3 0x00000033u                  /**< '3' */
#define MORTARK_4 0x00000034u                  /**< '4' */
#define MORTARK_5 0x00000035u                  /**< '5' */
#define MORTARK_6 0x00000036u                  /**< '6' */
#define MORTARK_7 0x00000037u                  /**< '7' */
#define MORTARK_8 0x00000038u                  /**< '8' */
#define MORTARK_9 0x00000039u                  /**< '9' */
#define MORTARK_COLON 0x0000003au              /**< ':' */
#define MORTARK_SEMICOLON 0x0000003bu          /**< ';' */
#define MORTARK_LESS 0x0000003cu               /**< '<' */
#define MORTARK_EQUALS 0x0000003du             /**< '=' */
#define MORTARK_GREATER 0x0000003eu            /**< '>' */
#define MORTARK_QUESTION 0x0000003fu           /**< '?' */
#define MORTARK_AT 0x00000040u                 /**< '@' */
#define MORTARK_LEFTBRACKET 0x0000005bu        /**< '[' */
#define MORTARK_BACKSLASH 0x0000005cu          /**< '\\' */
#define MORTARK_RIGHTBRACKET 0x0000005du       /**< ']' */
#define MORTARK_CARET 0x0000005eu              /**< '^' */
#define MORTARK_UNDERSCORE 0x0000005fu         /**< '_' */
#define MORTARK_GRAVE 0x00000060u              /**< '`' */
#define MORTARK_A 0x00000061u                  /**< 'a' */
#define MORTARK_B 0x00000062u                  /**< 'b' */
#define MORTARK_C 0x00000063u                  /**< 'c' */
#define MORTARK_D 0x00000064u                  /**< 'd' */
#define MORTARK_E 0x00000065u                  /**< 'e' */
#define MORTARK_F 0x00000066u                  /**< 'f' */
#define MORTARK_G 0x00000067u                  /**< 'g' */
#define MORTARK_H 0x00000068u                  /**< 'h' */
#define MORTARK_I 0x00000069u                  /**< 'i' */
#define MORTARK_J 0x0000006au                  /**< 'j' */
#define MORTARK_K 0x0000006bu                  /**< 'k' */
#define MORTARK_L 0x0000006cu                  /**< 'l' */
#define MORTARK_M 0x0000006du                  /**< 'm' */
#define MORTARK_N 0x0000006eu                  /**< 'n' */
#define MORTARK_O 0x0000006fu                  /**< 'o' */
#define MORTARK_P 0x00000070u                  /**< 'p' */
#define MORTARK_Q 0x00000071u                  /**< 'q' */
#define MORTARK_R 0x00000072u                  /**< 'r' */
#define MORTARK_S 0x00000073u                  /**< 's' */
#define MORTARK_T 0x00000074u                  /**< 't' */
#define MORTARK_U 0x00000075u                  /**< 'u' */
#define MORTARK_V 0x00000076u                  /**< 'v' */
#define MORTARK_W 0x00000077u                  /**< 'w' */
#define MORTARK_X 0x00000078u                  /**< 'x' */
#define MORTARK_Y 0x00000079u                  /**< 'y' */
#define MORTARK_Z 0x0000007au                  /**< 'z' */
#define MORTARK_LEFTBRACE 0x0000007bu          /**< '{' */
#define MORTARK_PIPE 0x0000007cu               /**< '|' */
#define MORTARK_RIGHTBRACE 0x0000007du         /**< '}' */
#define MORTARK_TILDE 0x0000007eu              /**< '~' */
#define MORTARK_DELETE 0x0000007fu             /**< '\x7F' */
#define MORTARK_PLUSMINUS 0x000000b1u          /**< '\xB1' */
#define MORTARK_CAPSLOCK 0x40000039u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CAPSLOCK) */
#define MORTARK_F1 0x4000003au                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F1) */
#define MORTARK_F2 0x4000003bu                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F2) */
#define MORTARK_F3 0x4000003cu                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F3) */
#define MORTARK_F4 0x4000003du                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F4) */
#define MORTARK_F5 0x4000003eu                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F5) */
#define MORTARK_F6 0x4000003fu                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F6) */
#define MORTARK_F7 0x40000040u                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F7) */
#define MORTARK_F8 0x40000041u                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F8) */
#define MORTARK_F9 0x40000042u                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F9) */
#define MORTARK_F10 0x40000043u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F10) */
#define MORTARK_F11 0x40000044u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F11) */
#define MORTARK_F12 0x40000045u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F12) */
#define MORTARK_PRINTSCREEN 0x40000046u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PRINTSCREEN) */
#define MORTARK_SCROLLLOCK 0x40000047u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SCROLLLOCK) */
#define MORTARK_PAUSE 0x40000048u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PAUSE) */
#define MORTARK_INSERT 0x40000049u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_INSERT) */
#define MORTARK_HOME 0x4000004au               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_HOME) */
#define MORTARK_PAGEUP 0x4000004bu             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PAGEUP) */
#define MORTARK_END 0x4000004du                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_END) */
#define MORTARK_PAGEDOWN 0x4000004eu           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PAGEDOWN) */
#define MORTARK_RIGHT 0x4000004fu              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RIGHT) */
#define MORTARK_LEFT 0x40000050u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_LEFT) */
#define MORTARK_DOWN 0x40000051u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_DOWN) */
#define MORTARK_UP 0x40000052u                 /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_UP) */
#define MORTARK_NUMLOCKCLEAR 0x40000053u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_NUMLOCKCLEAR) */
#define MORTARK_KP_DIVIDE 0x40000054u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_DIVIDE) */
#define MORTARK_KP_MULTIPLY 0x40000055u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MULTIPLY) */
#define MORTARK_KP_MINUS 0x40000056u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MINUS) */
#define MORTARK_KP_PLUS 0x40000057u            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_PLUS) */
#define MORTARK_KP_ENTER 0x40000058u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_ENTER) */
#define MORTARK_KP_1 0x40000059u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_1) */
#define MORTARK_KP_2 0x4000005au               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_2) */
#define MORTARK_KP_3 0x4000005bu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_3) */
#define MORTARK_KP_4 0x4000005cu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_4) */
#define MORTARK_KP_5 0x4000005du               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_5) */
#define MORTARK_KP_6 0x4000005eu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_6) */
#define MORTARK_KP_7 0x4000005fu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_7) */
#define MORTARK_KP_8 0x40000060u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_8) */
#define MORTARK_KP_9 0x40000061u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_9) */
#define MORTARK_KP_0 0x40000062u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_0) */
#define MORTARK_KP_PERIOD 0x40000063u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_PERIOD) */
#define MORTARK_APPLICATION 0x40000065u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_APPLICATION) */
#define MORTARK_POWER 0x40000066u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_POWER) */
#define MORTARK_KP_EQUALS 0x40000067u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_EQUALS) */
#define MORTARK_F13 0x40000068u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F13) */
#define MORTARK_F14 0x40000069u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F14) */
#define MORTARK_F15 0x4000006au                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F15) */
#define MORTARK_F16 0x4000006bu                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F16) */
#define MORTARK_F17 0x4000006cu                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F17) */
#define MORTARK_F18 0x4000006du                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F18) */
#define MORTARK_F19 0x4000006eu                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F19) */
#define MORTARK_F20 0x4000006fu                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F20) */
#define MORTARK_F21 0x40000070u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F21) */
#define MORTARK_F22 0x40000071u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F22) */
#define MORTARK_F23 0x40000072u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F23) */
#define MORTARK_F24 0x40000073u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_F24) */
#define MORTARK_EXECUTE 0x40000074u            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_EXECUTE) */
#define MORTARK_HELP 0x40000075u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_HELP) */
#define MORTARK_MENU 0x40000076u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MENU) */
#define MORTARK_SELECT 0x40000077u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SELECT) */
#define MORTARK_STOP 0x40000078u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_STOP) */
#define MORTARK_AGAIN 0x40000079u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AGAIN) */
#define MORTARK_UNDO 0x4000007au               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_UNDO) */
#define MORTARK_CUT 0x4000007bu                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CUT) */
#define MORTARK_COPY 0x4000007cu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_COPY) */
#define MORTARK_PASTE 0x4000007du              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PASTE) */
#define MORTARK_FIND 0x4000007eu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_FIND) */
#define MORTARK_MUTE 0x4000007fu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MUTE) */
#define MORTARK_VOLUMEUP 0x40000080u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_VOLUMEUP) */
#define MORTARK_VOLUMEDOWN 0x40000081u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_VOLUMEDOWN) */
#define MORTARK_KP_COMMA 0x40000085u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_COMMA) */
#define MORTARK_KP_EQUALSAS400 0x40000086u     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_EQUALSAS400) */
#define MORTARK_ALTERASE 0x40000099u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_ALTERASE) */
#define MORTARK_SYSREQ 0x4000009au             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SYSREQ) */
#define MORTARK_CANCEL 0x4000009bu             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CANCEL) */
#define MORTARK_CLEAR 0x4000009cu              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CLEAR) */
#define MORTARK_PRIOR 0x4000009du              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_PRIOR) */
#define MORTARK_RETURN2 0x4000009eu            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RETURN2) */
#define MORTARK_SEPARATOR 0x4000009fu          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SEPARATOR) */
#define MORTARK_OUT 0x400000a0u                /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_OUT) */
#define MORTARK_OPER 0x400000a1u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_OPER) */
#define MORTARK_CLEARAGAIN 0x400000a2u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CLEARAGAIN) */
#define MORTARK_CRSEL 0x400000a3u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CRSEL) */
#define MORTARK_EXSEL 0x400000a4u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_EXSEL) */
#define MORTARK_KP_00 0x400000b0u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_00) */
#define MORTARK_KP_000 0x400000b1u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_000) */
#define MORTARK_THOUSANDSSEPARATOR 0x400000b2u /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_THOUSANDSSEPARATOR) */
#define MORTARK_DECIMALSEPARATOR 0x400000b3u   /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_DECIMALSEPARATOR) */
#define MORTARK_CURRENCYUNIT 0x400000b4u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CURRENCYUNIT) */
#define MORTARK_CURRENCYSUBUNIT 0x400000b5u    /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CURRENCYSUBUNIT) */
#define MORTARK_KP_LEFTPAREN 0x400000b6u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_LEFTPAREN) */
#define MORTARK_KP_RIGHTPAREN 0x400000b7u      /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_RIGHTPAREN) */
#define MORTARK_KP_LEFTBRACE 0x400000b8u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_LEFTBRACE) */
#define MORTARK_KP_RIGHTBRACE 0x400000b9u      /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_RIGHTBRACE) */
#define MORTARK_KP_TAB 0x400000bau             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_TAB) */
#define MORTARK_KP_BACKSPACE 0x400000bbu       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_BACKSPACE) */
#define MORTARK_KP_A 0x400000bcu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_A) */
#define MORTARK_KP_B 0x400000bdu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_B) */
#define MORTARK_KP_C 0x400000beu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_C) */
#define MORTARK_KP_D 0x400000bfu               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_D) */
#define MORTARK_KP_E 0x400000c0u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_E) */
#define MORTARK_KP_F 0x400000c1u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_F) */
#define MORTARK_KP_XOR 0x400000c2u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_XOR) */
#define MORTARK_KP_POWER 0x400000c3u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_POWER) */
#define MORTARK_KP_PERCENT 0x400000c4u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_PERCENT) */
#define MORTARK_KP_LESS 0x400000c5u            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_LESS) */
#define MORTARK_KP_GREATER 0x400000c6u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_GREATER) */
#define MORTARK_KP_AMPERSAND 0x400000c7u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_AMPERSAND) */
#define MORTARK_KP_DBLAMPERSAND 0x400000c8u    /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_DBLAMPERSAND) */
#define MORTARK_KP_VERTICALBAR 0x400000c9u     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_VERTICALBAR) */
#define MORTARK_KP_DBLVERTICALBAR 0x400000cau  /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_DBLVERTICALBAR) */
#define MORTARK_KP_COLON 0x400000cbu           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_COLON) */
#define MORTARK_KP_HASH 0x400000ccu            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_HASH) */
#define MORTARK_KP_SPACE 0x400000cdu           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_SPACE) */
#define MORTARK_KP_AT 0x400000ceu              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_AT) */
#define MORTARK_KP_EXCLAM 0x400000cfu          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_EXCLAM) */
#define MORTARK_KP_MEMSTORE 0x400000d0u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMSTORE) */
#define MORTARK_KP_MEMRECALL 0x400000d1u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMRECALL) */
#define MORTARK_KP_MEMCLEAR 0x400000d2u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMCLEAR) */
#define MORTARK_KP_MEMADD 0x400000d3u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMADD) */
#define MORTARK_KP_MEMSUBTRACT 0x400000d4u     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMSUBTRACT) */
#define MORTARK_KP_MEMMULTIPLY 0x400000d5u     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMMULTIPLY) */
#define MORTARK_KP_MEMDIVIDE 0x400000d6u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_MEMDIVIDE) */
#define MORTARK_KP_PLUSMINUS 0x400000d7u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_PLUSMINUS) */
#define MORTARK_KP_CLEAR 0x400000d8u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_CLEAR) */
#define MORTARK_KP_CLEARENTRY 0x400000d9u      /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_CLEARENTRY) */
#define MORTARK_KP_BINARY 0x400000dau          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_BINARY) */
#define MORTARK_KP_OCTAL 0x400000dbu           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_OCTAL) */
#define MORTARK_KP_DECIMAL 0x400000dcu         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_DECIMAL) */
#define MORTARK_KP_HEXADECIMAL 0x400000ddu     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_KP_HEXADECIMAL) */
#define MORTARK_LCTRL 0x400000e0u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_LCTRL) */
#define MORTARK_LSHIFT 0x400000e1u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_LSHIFT) */
#define MORTARK_LALT 0x400000e2u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_LALT) */
#define MORTARK_LGUI 0x400000e3u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_LGUI) */
#define MORTARK_RCTRL 0x400000e4u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RCTRL) */
#define MORTARK_RSHIFT 0x400000e5u             /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RSHIFT) */
#define MORTARK_RALT 0x400000e6u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RALT) */
#define MORTARK_RGUI 0x400000e7u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_RGUI) */
#define MORTARK_MODE 0x40000101u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MODE) */
#define MORTARK_SLEEP 0x40000102u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SLEEP) */
#define MORTARK_WAKE 0x40000103u               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_WAKE) */
#define MORTARK_CHANNEL_INCREMENT 0x40000104u  /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CHANNEL_INCREMENT) */
#define MORTARK_CHANNEL_DECREMENT 0x40000105u  /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CHANNEL_DECREMENT) */
#define MORTARK_MEDIA_PLAY 0x40000106u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_PLAY) */
#define MORTARK_MEDIA_PAUSE 0x40000107u        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_PAUSE) */
#define MORTARK_MEDIA_RECORD 0x40000108u       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_RECORD) */
#define MORTARK_MEDIA_FAST_FORWARD 0x40000109u /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_FAST_FORWARD) */
#define MORTARK_MEDIA_REWIND 0x4000010au       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_REWIND) */
#define MORTARK_MEDIA_NEXT_TRACK 0x4000010bu   /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_NEXT_TRACK) */
#define MORTARK_MEDIA_PREVIOUS_TRACK                                                                                   \
	0x4000010cu                               /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_PREVIOUS_TRACK) */
#define MORTARK_MEDIA_STOP 0x4000010du        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_STOP) */
#define MORTARK_MEDIA_EJECT 0x4000010eu       /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_EJECT) */
#define MORTARK_MEDIA_PLAY_PAUSE 0x4000010fu  /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_PLAY_PAUSE) */
#define MORTARK_MEDIA_SELECT 0x40000110u      /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_MEDIA_SELECT) */
#define MORTARK_AC_NEW 0x40000111u            /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_NEW) */
#define MORTARK_AC_OPEN 0x40000112u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_OPEN) */
#define MORTARK_AC_CLOSE 0x40000113u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_CLOSE) */
#define MORTARK_AC_EXIT 0x40000114u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_EXIT) */
#define MORTARK_AC_SAVE 0x40000115u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_SAVE) */
#define MORTARK_AC_PRINT 0x40000116u          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_PRINT) */
#define MORTARK_AC_PROPERTIES 0x40000117u     /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_PROPERTIES) */
#define MORTARK_AC_SEARCH 0x40000118u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_SEARCH) */
#define MORTARK_AC_HOME 0x40000119u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_HOME) */
#define MORTARK_AC_BACK 0x4000011au           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_BACK) */
#define MORTARK_AC_FORWARD 0x4000011bu        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_FORWARD) */
#define MORTARK_AC_STOP 0x4000011cu           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_STOP) */
#define MORTARK_AC_REFRESH 0x4000011du        /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_REFRESH) */
#define MORTARK_AC_BOOKMARKS 0x4000011eu      /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_AC_BOOKMARKS) */
#define MORTARK_SOFTLEFT 0x4000011fu          /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SOFTLEFT) */
#define MORTARK_SOFTRIGHT 0x40000120u         /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_SOFTRIGHT) */
#define MORTARK_CALL 0x40000121u              /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_CALL) */
#define MORTARK_ENDCALL 0x40000122u           /**< MORTAR_SCANCODE_TO_KEYCODE(MORTAR_SCANCODE_ENDCALL) */
#define MORTARK_LEFT_TAB 0x20000001u          /**< Extended key Left Tab */
#define MORTARK_LEVEL5_SHIFT 0x20000002u      /**< Extended key Level 5 Shift */
#define MORTARK_MULTI_KEY_COMPOSE 0x20000003u /**< Extended key Multi-key Compose */
#define MORTARK_LMETA 0x20000004u             /**< Extended key Left Meta */
#define MORTARK_RMETA 0x20000005u             /**< Extended key Right Meta */
#define MORTARK_LHYPER 0x20000006u            /**< Extended key Left Hyper */
#define MORTARK_RHYPER 0x20000007u            /**< Extended key Right Hyper */

/**
 * Valid key modifiers (possibly OR'd together).
 *
 * \since This datatype is available since SDL 3.2.0.
 */
typedef uint16_t MORTAR_Keymod;

#define MORTAR_KMOD_NONE 0x0000u   /**< no modifier is applicable. */
#define MORTAR_KMOD_LSHIFT 0x0001u /**< the left Shift key is down. */
#define MORTAR_KMOD_RSHIFT 0x0002u /**< the right Shift key is down. */
#define MORTAR_KMOD_LEVEL5 0x0004u /**< the Level 5 Shift key is down. */
#define MORTAR_KMOD_LCTRL 0x0040u  /**< the left Ctrl (Control) key is down. */
#define MORTAR_KMOD_RCTRL 0x0080u  /**< the right Ctrl (Control) key is down. */
#define MORTAR_KMOD_LALT 0x0100u   /**< the left Alt key is down. */
#define MORTAR_KMOD_RALT 0x0200u   /**< the right Alt key is down. */
#define MORTAR_KMOD_LGUI 0x0400u   /**< the left GUI key (often the Windows key) is down. */
#define MORTAR_KMOD_RGUI 0x0800u   /**< the right GUI key (often the Windows key) is down. */
#define MORTAR_KMOD_NUM 0x1000u    /**< the Num Lock key (may be located on an extended keypad) is down. */
#define MORTAR_KMOD_CAPS 0x2000u   /**< the Caps Lock key is down. */
#define MORTAR_KMOD_MODE 0x4000u   /**< the !AltGr key is down. */
#define MORTAR_KMOD_SCROLL 0x8000u /**< the Scroll Lock key is down. */
#define MORTAR_KMOD_CTRL (MORTAR_KMOD_LCTRL | MORTAR_KMOD_RCTRL)    /**< Any Ctrl key is down. */
#define MORTAR_KMOD_SHIFT (MORTAR_KMOD_LSHIFT | MORTAR_KMOD_RSHIFT) /**< Any Shift key is down. */
#define MORTAR_KMOD_ALT (MORTAR_KMOD_LALT | MORTAR_KMOD_RALT)       /**< Any Alt key is down. */
#define MORTAR_KMOD_GUI (MORTAR_KMOD_LGUI | MORTAR_KMOD_RGUI)       /**< Any GUI key is down. */

#include "mortar_end.h"
