#include "mortar/mortar_keycode.h"
#include "sdl3_internal.h"

SDL_Keycode keycode_mortar_to_sdl3(MORTAR_Keycode keycode)
{
	switch (keycode) {
	case MORTARK_UNKNOWN:
		return SDLK_UNKNOWN;
	case MORTARK_RETURN:
		return SDLK_RETURN;
	case MORTARK_ESCAPE:
		return SDLK_ESCAPE;
	case MORTARK_BACKSPACE:
		return SDLK_BACKSPACE;
	case MORTARK_TAB:
		return SDLK_TAB;
	case MORTARK_SPACE:
		return SDLK_SPACE;
	case MORTARK_EXCLAIM:
		return SDLK_EXCLAIM;
	case MORTARK_DBLAPOSTROPHE:
		return SDLK_DBLAPOSTROPHE;
	case MORTARK_HASH:
		return SDLK_HASH;
	case MORTARK_DOLLAR:
		return SDLK_DOLLAR;
	case MORTARK_PERCENT:
		return SDLK_PERCENT;
	case MORTARK_AMPERSAND:
		return SDLK_AMPERSAND;
	case MORTARK_APOSTROPHE:
		return SDLK_APOSTROPHE;
	case MORTARK_LEFTPAREN:
		return SDLK_LEFTPAREN;
	case MORTARK_RIGHTPAREN:
		return SDLK_RIGHTPAREN;
	case MORTARK_ASTERISK:
		return SDLK_ASTERISK;
	case MORTARK_PLUS:
		return SDLK_PLUS;
	case MORTARK_COMMA:
		return SDLK_COMMA;
	case MORTARK_MINUS:
		return SDLK_MINUS;
	case MORTARK_PERIOD:
		return SDLK_PERIOD;
	case MORTARK_SLASH:
		return SDLK_SLASH;
	case MORTARK_0:
		return SDLK_0;
	case MORTARK_1:
		return SDLK_1;
	case MORTARK_2:
		return SDLK_2;
	case MORTARK_3:
		return SDLK_3;
	case MORTARK_4:
		return SDLK_4;
	case MORTARK_5:
		return SDLK_5;
	case MORTARK_6:
		return SDLK_6;
	case MORTARK_7:
		return SDLK_7;
	case MORTARK_8:
		return SDLK_8;
	case MORTARK_9:
		return SDLK_9;
	case MORTARK_COLON:
		return SDLK_COLON;
	case MORTARK_SEMICOLON:
		return SDLK_SEMICOLON;
	case MORTARK_LESS:
		return SDLK_LESS;
	case MORTARK_EQUALS:
		return SDLK_EQUALS;
	case MORTARK_GREATER:
		return SDLK_GREATER;
	case MORTARK_QUESTION:
		return SDLK_QUESTION;
	case MORTARK_AT:
		return SDLK_AT;
	case MORTARK_LEFTBRACKET:
		return SDLK_LEFTBRACKET;
	case MORTARK_BACKSLASH:
		return SDLK_BACKSLASH;
	case MORTARK_RIGHTBRACKET:
		return SDLK_RIGHTBRACKET;
	case MORTARK_CARET:
		return SDLK_CARET;
	case MORTARK_UNDERSCORE:
		return SDLK_UNDERSCORE;
	case MORTARK_GRAVE:
		return SDLK_GRAVE;
	case MORTARK_A:
		return SDLK_A;
	case MORTARK_B:
		return SDLK_B;
	case MORTARK_C:
		return SDLK_C;
	case MORTARK_D:
		return SDLK_D;
	case MORTARK_E:
		return SDLK_E;
	case MORTARK_F:
		return SDLK_F;
	case MORTARK_G:
		return SDLK_G;
	case MORTARK_H:
		return SDLK_H;
	case MORTARK_I:
		return SDLK_I;
	case MORTARK_J:
		return SDLK_J;
	case MORTARK_K:
		return SDLK_K;
	case MORTARK_L:
		return SDLK_L;
	case MORTARK_M:
		return SDLK_M;
	case MORTARK_N:
		return SDLK_N;
	case MORTARK_O:
		return SDLK_O;
	case MORTARK_P:
		return SDLK_P;
	case MORTARK_Q:
		return SDLK_Q;
	case MORTARK_R:
		return SDLK_R;
	case MORTARK_S:
		return SDLK_S;
	case MORTARK_T:
		return SDLK_T;
	case MORTARK_U:
		return SDLK_U;
	case MORTARK_V:
		return SDLK_V;
	case MORTARK_W:
		return SDLK_W;
	case MORTARK_X:
		return SDLK_X;
	case MORTARK_Y:
		return SDLK_Y;
	case MORTARK_Z:
		return SDLK_Z;
	case MORTARK_LEFTBRACE:
		return SDLK_LEFTBRACE;
	case MORTARK_PIPE:
		return SDLK_PIPE;
	case MORTARK_RIGHTBRACE:
		return SDLK_RIGHTBRACE;
	case MORTARK_TILDE:
		return SDLK_TILDE;
	case MORTARK_DELETE:
		return SDLK_DELETE;
	case MORTARK_PLUSMINUS:
		return SDLK_PLUSMINUS;
	case MORTARK_CAPSLOCK:
		return SDLK_CAPSLOCK;
	case MORTARK_F1:
		return SDLK_F1;
	case MORTARK_F2:
		return SDLK_F2;
	case MORTARK_F3:
		return SDLK_F3;
	case MORTARK_F4:
		return SDLK_F4;
	case MORTARK_F5:
		return SDLK_F5;
	case MORTARK_F6:
		return SDLK_F6;
	case MORTARK_F7:
		return SDLK_F7;
	case MORTARK_F8:
		return SDLK_F8;
	case MORTARK_F9:
		return SDLK_F9;
	case MORTARK_F10:
		return SDLK_F10;
	case MORTARK_F11:
		return SDLK_F11;
	case MORTARK_F12:
		return SDLK_F12;
	case MORTARK_PRINTSCREEN:
		return SDLK_PRINTSCREEN;
	case MORTARK_SCROLLLOCK:
		return SDLK_SCROLLLOCK;
	case MORTARK_PAUSE:
		return SDLK_PAUSE;
	case MORTARK_INSERT:
		return SDLK_INSERT;
	case MORTARK_HOME:
		return SDLK_HOME;
	case MORTARK_PAGEUP:
		return SDLK_PAGEUP;
	case MORTARK_END:
		return SDLK_END;
	case MORTARK_PAGEDOWN:
		return SDLK_PAGEDOWN;
	case MORTARK_RIGHT:
		return SDLK_RIGHT;
	case MORTARK_LEFT:
		return SDLK_LEFT;
	case MORTARK_DOWN:
		return SDLK_DOWN;
	case MORTARK_UP:
		return SDLK_UP;
	case MORTARK_NUMLOCKCLEAR:
		return SDLK_NUMLOCKCLEAR;
	case MORTARK_KP_DIVIDE:
		return SDLK_KP_DIVIDE;
	case MORTARK_KP_MULTIPLY:
		return SDLK_KP_MULTIPLY;
	case MORTARK_KP_MINUS:
		return SDLK_KP_MINUS;
	case MORTARK_KP_PLUS:
		return SDLK_KP_PLUS;
	case MORTARK_KP_ENTER:
		return SDLK_KP_ENTER;
	case MORTARK_KP_1:
		return SDLK_KP_1;
	case MORTARK_KP_2:
		return SDLK_KP_2;
	case MORTARK_KP_3:
		return SDLK_KP_3;
	case MORTARK_KP_4:
		return SDLK_KP_4;
	case MORTARK_KP_5:
		return SDLK_KP_5;
	case MORTARK_KP_6:
		return SDLK_KP_6;
	case MORTARK_KP_7:
		return SDLK_KP_7;
	case MORTARK_KP_8:
		return SDLK_KP_8;
	case MORTARK_KP_9:
		return SDLK_KP_9;
	case MORTARK_KP_0:
		return SDLK_KP_0;
	case MORTARK_KP_PERIOD:
		return SDLK_KP_PERIOD;
	case MORTARK_APPLICATION:
		return SDLK_APPLICATION;
	case MORTARK_POWER:
		return SDLK_POWER;
	case MORTARK_KP_EQUALS:
		return SDLK_KP_EQUALS;
	case MORTARK_F13:
		return SDLK_F13;
	case MORTARK_F14:
		return SDLK_F14;
	case MORTARK_F15:
		return SDLK_F15;
	case MORTARK_F16:
		return SDLK_F16;
	case MORTARK_F17:
		return SDLK_F17;
	case MORTARK_F18:
		return SDLK_F18;
	case MORTARK_F19:
		return SDLK_F19;
	case MORTARK_F20:
		return SDLK_F20;
	case MORTARK_F21:
		return SDLK_F21;
	case MORTARK_F22:
		return SDLK_F22;
	case MORTARK_F23:
		return SDLK_F23;
	case MORTARK_F24:
		return SDLK_F24;
	case MORTARK_EXECUTE:
		return SDLK_EXECUTE;
	case MORTARK_HELP:
		return SDLK_HELP;
	case MORTARK_MENU:
		return SDLK_MENU;
	case MORTARK_SELECT:
		return SDLK_SELECT;
	case MORTARK_STOP:
		return SDLK_STOP;
	case MORTARK_AGAIN:
		return SDLK_AGAIN;
	case MORTARK_UNDO:
		return SDLK_UNDO;
	case MORTARK_CUT:
		return SDLK_CUT;
	case MORTARK_COPY:
		return SDLK_COPY;
	case MORTARK_PASTE:
		return SDLK_PASTE;
	case MORTARK_FIND:
		return SDLK_FIND;
	case MORTARK_MUTE:
		return SDLK_MUTE;
	case MORTARK_VOLUMEUP:
		return SDLK_VOLUMEUP;
	case MORTARK_VOLUMEDOWN:
		return SDLK_VOLUMEDOWN;
	case MORTARK_KP_COMMA:
		return SDLK_KP_COMMA;
	case MORTARK_KP_EQUALSAS400:
		return SDLK_KP_EQUALSAS400;
	case MORTARK_ALTERASE:
		return SDLK_ALTERASE;
	case MORTARK_SYSREQ:
		return SDLK_SYSREQ;
	case MORTARK_CANCEL:
		return SDLK_CANCEL;
	case MORTARK_CLEAR:
		return SDLK_CLEAR;
	case MORTARK_PRIOR:
		return SDLK_PRIOR;
	case MORTARK_RETURN2:
		return SDLK_RETURN2;
	case MORTARK_SEPARATOR:
		return SDLK_SEPARATOR;
	case MORTARK_OUT:
		return SDLK_OUT;
	case MORTARK_OPER:
		return SDLK_OPER;
	case MORTARK_CLEARAGAIN:
		return SDLK_CLEARAGAIN;
	case MORTARK_CRSEL:
		return SDLK_CRSEL;
	case MORTARK_EXSEL:
		return SDLK_EXSEL;
	case MORTARK_KP_00:
		return SDLK_KP_00;
	case MORTARK_KP_000:
		return SDLK_KP_000;
	case MORTARK_THOUSANDSSEPARATOR:
		return SDLK_THOUSANDSSEPARATOR;
	case MORTARK_DECIMALSEPARATOR:
		return SDLK_DECIMALSEPARATOR;
	case MORTARK_CURRENCYUNIT:
		return SDLK_CURRENCYUNIT;
	case MORTARK_CURRENCYSUBUNIT:
		return SDLK_CURRENCYSUBUNIT;
	case MORTARK_KP_LEFTPAREN:
		return SDLK_KP_LEFTPAREN;
	case MORTARK_KP_RIGHTPAREN:
		return SDLK_KP_RIGHTPAREN;
	case MORTARK_KP_LEFTBRACE:
		return SDLK_KP_LEFTBRACE;
	case MORTARK_KP_RIGHTBRACE:
		return SDLK_KP_RIGHTBRACE;
	case MORTARK_KP_TAB:
		return SDLK_KP_TAB;
	case MORTARK_KP_BACKSPACE:
		return SDLK_KP_BACKSPACE;
	case MORTARK_KP_A:
		return SDLK_KP_A;
	case MORTARK_KP_B:
		return SDLK_KP_B;
	case MORTARK_KP_C:
		return SDLK_KP_C;
	case MORTARK_KP_D:
		return SDLK_KP_D;
	case MORTARK_KP_E:
		return SDLK_KP_E;
	case MORTARK_KP_F:
		return SDLK_KP_F;
	case MORTARK_KP_XOR:
		return SDLK_KP_XOR;
	case MORTARK_KP_POWER:
		return SDLK_KP_POWER;
	case MORTARK_KP_PERCENT:
		return SDLK_KP_PERCENT;
	case MORTARK_KP_LESS:
		return SDLK_KP_LESS;
	case MORTARK_KP_GREATER:
		return SDLK_KP_GREATER;
	case MORTARK_KP_AMPERSAND:
		return SDLK_KP_AMPERSAND;
	case MORTARK_KP_DBLAMPERSAND:
		return SDLK_KP_DBLAMPERSAND;
	case MORTARK_KP_VERTICALBAR:
		return SDLK_KP_VERTICALBAR;
	case MORTARK_KP_DBLVERTICALBAR:
		return SDLK_KP_DBLVERTICALBAR;
	case MORTARK_KP_COLON:
		return SDLK_KP_COLON;
	case MORTARK_KP_HASH:
		return SDLK_KP_HASH;
	case MORTARK_KP_SPACE:
		return SDLK_KP_SPACE;
	case MORTARK_KP_AT:
		return SDLK_KP_AT;
	case MORTARK_KP_EXCLAM:
		return SDLK_KP_EXCLAM;
	case MORTARK_KP_MEMSTORE:
		return SDLK_KP_MEMSTORE;
	case MORTARK_KP_MEMRECALL:
		return SDLK_KP_MEMRECALL;
	case MORTARK_KP_MEMCLEAR:
		return SDLK_KP_MEMCLEAR;
	case MORTARK_KP_MEMADD:
		return SDLK_KP_MEMADD;
	case MORTARK_KP_MEMSUBTRACT:
		return SDLK_KP_MEMSUBTRACT;
	case MORTARK_KP_MEMMULTIPLY:
		return SDLK_KP_MEMMULTIPLY;
	case MORTARK_KP_MEMDIVIDE:
		return SDLK_KP_MEMDIVIDE;
	case MORTARK_KP_PLUSMINUS:
		return SDLK_KP_PLUSMINUS;
	case MORTARK_KP_CLEAR:
		return SDLK_KP_CLEAR;
	case MORTARK_KP_CLEARENTRY:
		return SDLK_KP_CLEARENTRY;
	case MORTARK_KP_BINARY:
		return SDLK_KP_BINARY;
	case MORTARK_KP_OCTAL:
		return SDLK_KP_OCTAL;
	case MORTARK_KP_DECIMAL:
		return SDLK_KP_DECIMAL;
	case MORTARK_KP_HEXADECIMAL:
		return SDLK_KP_HEXADECIMAL;
	case MORTARK_LCTRL:
		return SDLK_LCTRL;
	case MORTARK_LSHIFT:
		return SDLK_LSHIFT;
	case MORTARK_LALT:
		return SDLK_LALT;
	case MORTARK_LGUI:
		return SDLK_LGUI;
	case MORTARK_RCTRL:
		return SDLK_RCTRL;
	case MORTARK_RSHIFT:
		return SDLK_RSHIFT;
	case MORTARK_RALT:
		return SDLK_RALT;
	case MORTARK_RGUI:
		return SDLK_RGUI;
	case MORTARK_MODE:
		return SDLK_MODE;
	case MORTARK_SLEEP:
		return SDLK_SLEEP;
	case MORTARK_WAKE:
		return SDLK_WAKE;
	case MORTARK_CHANNEL_INCREMENT:
		return SDLK_CHANNEL_INCREMENT;
	case MORTARK_CHANNEL_DECREMENT:
		return SDLK_CHANNEL_DECREMENT;
	case MORTARK_MEDIA_PLAY:
		return SDLK_MEDIA_PLAY;
	case MORTARK_MEDIA_PAUSE:
		return SDLK_MEDIA_PAUSE;
	case MORTARK_MEDIA_RECORD:
		return SDLK_MEDIA_RECORD;
	case MORTARK_MEDIA_FAST_FORWARD:
		return SDLK_MEDIA_FAST_FORWARD;
	case MORTARK_MEDIA_REWIND:
		return SDLK_MEDIA_REWIND;
	case MORTARK_MEDIA_NEXT_TRACK:
		return SDLK_MEDIA_NEXT_TRACK;
	case MORTARK_MEDIA_PREVIOUS_TRACK:
		return SDLK_MEDIA_PREVIOUS_TRACK;
	case MORTARK_MEDIA_STOP:
		return SDLK_MEDIA_STOP;
	case MORTARK_MEDIA_EJECT:
		return SDLK_MEDIA_EJECT;
	case MORTARK_MEDIA_PLAY_PAUSE:
		return SDLK_MEDIA_PLAY_PAUSE;
	case MORTARK_MEDIA_SELECT:
		return SDLK_MEDIA_SELECT;
	case MORTARK_AC_NEW:
		return SDLK_AC_NEW;
	case MORTARK_AC_OPEN:
		return SDLK_AC_OPEN;
	case MORTARK_AC_CLOSE:
		return SDLK_AC_CLOSE;
	case MORTARK_AC_EXIT:
		return SDLK_AC_EXIT;
	case MORTARK_AC_SAVE:
		return SDLK_AC_SAVE;
	case MORTARK_AC_PRINT:
		return SDLK_AC_PRINT;
	case MORTARK_AC_PROPERTIES:
		return SDLK_AC_PROPERTIES;
	case MORTARK_AC_SEARCH:
		return SDLK_AC_SEARCH;
	case MORTARK_AC_HOME:
		return SDLK_AC_HOME;
	case MORTARK_AC_BACK:
		return SDLK_AC_BACK;
	case MORTARK_AC_FORWARD:
		return SDLK_AC_FORWARD;
	case MORTARK_AC_STOP:
		return SDLK_AC_STOP;
	case MORTARK_AC_REFRESH:
		return SDLK_AC_REFRESH;
	case MORTARK_AC_BOOKMARKS:
		return SDLK_AC_BOOKMARKS;
	case MORTARK_SOFTLEFT:
		return SDLK_SOFTLEFT;
	case MORTARK_SOFTRIGHT:
		return SDLK_SOFTRIGHT;
	case MORTARK_CALL:
		return SDLK_CALL;
	case MORTARK_ENDCALL:
		return SDLK_ENDCALL;
	case MORTARK_LEFT_TAB:
		return SDLK_LEFT_TAB;
	case MORTARK_LEVEL5_SHIFT:
		return SDLK_LEVEL5_SHIFT;
	case MORTARK_MULTI_KEY_COMPOSE:
		return SDLK_MULTI_KEY_COMPOSE;
	case MORTARK_LMETA:
		return SDLK_LMETA;
	case MORTARK_RMETA:
		return SDLK_RMETA;
	case MORTARK_LHYPER:
		return SDLK_LHYPER;
	case MORTARK_RHYPER:
		return SDLK_RHYPER;
	default:
		return keycode;
	}
}
MORTAR_Keycode keycode_sdl3_to_mortar(SDL_Keycode keycode)
{
	switch (keycode) {
	case SDLK_UNKNOWN:
		return MORTARK_UNKNOWN;
	case SDLK_RETURN:
		return MORTARK_RETURN;
	case SDLK_ESCAPE:
		return MORTARK_ESCAPE;
	case SDLK_BACKSPACE:
		return MORTARK_BACKSPACE;
	case SDLK_TAB:
		return MORTARK_TAB;
	case SDLK_SPACE:
		return MORTARK_SPACE;
	case SDLK_EXCLAIM:
		return MORTARK_EXCLAIM;
	case SDLK_DBLAPOSTROPHE:
		return MORTARK_DBLAPOSTROPHE;
	case SDLK_HASH:
		return MORTARK_HASH;
	case SDLK_DOLLAR:
		return MORTARK_DOLLAR;
	case SDLK_PERCENT:
		return MORTARK_PERCENT;
	case SDLK_AMPERSAND:
		return MORTARK_AMPERSAND;
	case SDLK_APOSTROPHE:
		return MORTARK_APOSTROPHE;
	case SDLK_LEFTPAREN:
		return MORTARK_LEFTPAREN;
	case SDLK_RIGHTPAREN:
		return MORTARK_RIGHTPAREN;
	case SDLK_ASTERISK:
		return MORTARK_ASTERISK;
	case SDLK_PLUS:
		return MORTARK_PLUS;
	case SDLK_COMMA:
		return MORTARK_COMMA;
	case SDLK_MINUS:
		return MORTARK_MINUS;
	case SDLK_PERIOD:
		return MORTARK_PERIOD;
	case SDLK_SLASH:
		return MORTARK_SLASH;
	case SDLK_0:
		return MORTARK_0;
	case SDLK_1:
		return MORTARK_1;
	case SDLK_2:
		return MORTARK_2;
	case SDLK_3:
		return MORTARK_3;
	case SDLK_4:
		return MORTARK_4;
	case SDLK_5:
		return MORTARK_5;
	case SDLK_6:
		return MORTARK_6;
	case SDLK_7:
		return MORTARK_7;
	case SDLK_8:
		return MORTARK_8;
	case SDLK_9:
		return MORTARK_9;
	case SDLK_COLON:
		return MORTARK_COLON;
	case SDLK_SEMICOLON:
		return MORTARK_SEMICOLON;
	case SDLK_LESS:
		return MORTARK_LESS;
	case SDLK_EQUALS:
		return MORTARK_EQUALS;
	case SDLK_GREATER:
		return MORTARK_GREATER;
	case SDLK_QUESTION:
		return MORTARK_QUESTION;
	case SDLK_AT:
		return MORTARK_AT;
	case SDLK_LEFTBRACKET:
		return MORTARK_LEFTBRACKET;
	case SDLK_BACKSLASH:
		return MORTARK_BACKSLASH;
	case SDLK_RIGHTBRACKET:
		return MORTARK_RIGHTBRACKET;
	case SDLK_CARET:
		return MORTARK_CARET;
	case SDLK_UNDERSCORE:
		return MORTARK_UNDERSCORE;
	case SDLK_GRAVE:
		return MORTARK_GRAVE;
	case SDLK_A:
		return MORTARK_A;
	case SDLK_B:
		return MORTARK_B;
	case SDLK_C:
		return MORTARK_C;
	case SDLK_D:
		return MORTARK_D;
	case SDLK_E:
		return MORTARK_E;
	case SDLK_F:
		return MORTARK_F;
	case SDLK_G:
		return MORTARK_G;
	case SDLK_H:
		return MORTARK_H;
	case SDLK_I:
		return MORTARK_I;
	case SDLK_J:
		return MORTARK_J;
	case SDLK_K:
		return MORTARK_K;
	case SDLK_L:
		return MORTARK_L;
	case SDLK_M:
		return MORTARK_M;
	case SDLK_N:
		return MORTARK_N;
	case SDLK_O:
		return MORTARK_O;
	case SDLK_P:
		return MORTARK_P;
	case SDLK_Q:
		return MORTARK_Q;
	case SDLK_R:
		return MORTARK_R;
	case SDLK_S:
		return MORTARK_S;
	case SDLK_T:
		return MORTARK_T;
	case SDLK_U:
		return MORTARK_U;
	case SDLK_V:
		return MORTARK_V;
	case SDLK_W:
		return MORTARK_W;
	case SDLK_X:
		return MORTARK_X;
	case SDLK_Y:
		return MORTARK_Y;
	case SDLK_Z:
		return MORTARK_Z;
	case SDLK_LEFTBRACE:
		return MORTARK_LEFTBRACE;
	case SDLK_PIPE:
		return MORTARK_PIPE;
	case SDLK_RIGHTBRACE:
		return MORTARK_RIGHTBRACE;
	case SDLK_TILDE:
		return MORTARK_TILDE;
	case SDLK_DELETE:
		return MORTARK_DELETE;
	case SDLK_PLUSMINUS:
		return MORTARK_PLUSMINUS;
	case SDLK_CAPSLOCK:
		return MORTARK_CAPSLOCK;
	case SDLK_F1:
		return MORTARK_F1;
	case SDLK_F2:
		return MORTARK_F2;
	case SDLK_F3:
		return MORTARK_F3;
	case SDLK_F4:
		return MORTARK_F4;
	case SDLK_F5:
		return MORTARK_F5;
	case SDLK_F6:
		return MORTARK_F6;
	case SDLK_F7:
		return MORTARK_F7;
	case SDLK_F8:
		return MORTARK_F8;
	case SDLK_F9:
		return MORTARK_F9;
	case SDLK_F10:
		return MORTARK_F10;
	case SDLK_F11:
		return MORTARK_F11;
	case SDLK_F12:
		return MORTARK_F12;
	case SDLK_PRINTSCREEN:
		return MORTARK_PRINTSCREEN;
	case SDLK_SCROLLLOCK:
		return MORTARK_SCROLLLOCK;
	case SDLK_PAUSE:
		return MORTARK_PAUSE;
	case SDLK_INSERT:
		return MORTARK_INSERT;
	case SDLK_HOME:
		return MORTARK_HOME;
	case SDLK_PAGEUP:
		return MORTARK_PAGEUP;
	case SDLK_END:
		return MORTARK_END;
	case SDLK_PAGEDOWN:
		return MORTARK_PAGEDOWN;
	case SDLK_RIGHT:
		return MORTARK_RIGHT;
	case SDLK_LEFT:
		return MORTARK_LEFT;
	case SDLK_DOWN:
		return MORTARK_DOWN;
	case SDLK_UP:
		return MORTARK_UP;
	case SDLK_NUMLOCKCLEAR:
		return MORTARK_NUMLOCKCLEAR;
	case SDLK_KP_DIVIDE:
		return MORTARK_KP_DIVIDE;
	case SDLK_KP_MULTIPLY:
		return MORTARK_KP_MULTIPLY;
	case SDLK_KP_MINUS:
		return MORTARK_KP_MINUS;
	case SDLK_KP_PLUS:
		return MORTARK_KP_PLUS;
	case SDLK_KP_ENTER:
		return MORTARK_KP_ENTER;
	case SDLK_KP_1:
		return MORTARK_KP_1;
	case SDLK_KP_2:
		return MORTARK_KP_2;
	case SDLK_KP_3:
		return MORTARK_KP_3;
	case SDLK_KP_4:
		return MORTARK_KP_4;
	case SDLK_KP_5:
		return MORTARK_KP_5;
	case SDLK_KP_6:
		return MORTARK_KP_6;
	case SDLK_KP_7:
		return MORTARK_KP_7;
	case SDLK_KP_8:
		return MORTARK_KP_8;
	case SDLK_KP_9:
		return MORTARK_KP_9;
	case SDLK_KP_0:
		return MORTARK_KP_0;
	case SDLK_KP_PERIOD:
		return MORTARK_KP_PERIOD;
	case SDLK_APPLICATION:
		return MORTARK_APPLICATION;
	case SDLK_POWER:
		return MORTARK_POWER;
	case SDLK_KP_EQUALS:
		return MORTARK_KP_EQUALS;
	case SDLK_F13:
		return MORTARK_F13;
	case SDLK_F14:
		return MORTARK_F14;
	case SDLK_F15:
		return MORTARK_F15;
	case SDLK_F16:
		return MORTARK_F16;
	case SDLK_F17:
		return MORTARK_F17;
	case SDLK_F18:
		return MORTARK_F18;
	case SDLK_F19:
		return MORTARK_F19;
	case SDLK_F20:
		return MORTARK_F20;
	case SDLK_F21:
		return MORTARK_F21;
	case SDLK_F22:
		return MORTARK_F22;
	case SDLK_F23:
		return MORTARK_F23;
	case SDLK_F24:
		return MORTARK_F24;
	case SDLK_EXECUTE:
		return MORTARK_EXECUTE;
	case SDLK_HELP:
		return MORTARK_HELP;
	case SDLK_MENU:
		return MORTARK_MENU;
	case SDLK_SELECT:
		return MORTARK_SELECT;
	case SDLK_STOP:
		return MORTARK_STOP;
	case SDLK_AGAIN:
		return MORTARK_AGAIN;
	case SDLK_UNDO:
		return MORTARK_UNDO;
	case SDLK_CUT:
		return MORTARK_CUT;
	case SDLK_COPY:
		return MORTARK_COPY;
	case SDLK_PASTE:
		return MORTARK_PASTE;
	case SDLK_FIND:
		return MORTARK_FIND;
	case SDLK_MUTE:
		return MORTARK_MUTE;
	case SDLK_VOLUMEUP:
		return MORTARK_VOLUMEUP;
	case SDLK_VOLUMEDOWN:
		return MORTARK_VOLUMEDOWN;
	case SDLK_KP_COMMA:
		return MORTARK_KP_COMMA;
	case SDLK_KP_EQUALSAS400:
		return MORTARK_KP_EQUALSAS400;
	case SDLK_ALTERASE:
		return MORTARK_ALTERASE;
	case SDLK_SYSREQ:
		return MORTARK_SYSREQ;
	case SDLK_CANCEL:
		return MORTARK_CANCEL;
	case SDLK_CLEAR:
		return MORTARK_CLEAR;
	case SDLK_PRIOR:
		return MORTARK_PRIOR;
	case SDLK_RETURN2:
		return MORTARK_RETURN2;
	case SDLK_SEPARATOR:
		return MORTARK_SEPARATOR;
	case SDLK_OUT:
		return MORTARK_OUT;
	case SDLK_OPER:
		return MORTARK_OPER;
	case SDLK_CLEARAGAIN:
		return MORTARK_CLEARAGAIN;
	case SDLK_CRSEL:
		return MORTARK_CRSEL;
	case SDLK_EXSEL:
		return MORTARK_EXSEL;
	case SDLK_KP_00:
		return MORTARK_KP_00;
	case SDLK_KP_000:
		return MORTARK_KP_000;
	case SDLK_THOUSANDSSEPARATOR:
		return MORTARK_THOUSANDSSEPARATOR;
	case SDLK_DECIMALSEPARATOR:
		return MORTARK_DECIMALSEPARATOR;
	case SDLK_CURRENCYUNIT:
		return MORTARK_CURRENCYUNIT;
	case SDLK_CURRENCYSUBUNIT:
		return MORTARK_CURRENCYSUBUNIT;
	case SDLK_KP_LEFTPAREN:
		return MORTARK_KP_LEFTPAREN;
	case SDLK_KP_RIGHTPAREN:
		return MORTARK_KP_RIGHTPAREN;
	case SDLK_KP_LEFTBRACE:
		return MORTARK_KP_LEFTBRACE;
	case SDLK_KP_RIGHTBRACE:
		return MORTARK_KP_RIGHTBRACE;
	case SDLK_KP_TAB:
		return MORTARK_KP_TAB;
	case SDLK_KP_BACKSPACE:
		return MORTARK_KP_BACKSPACE;
	case SDLK_KP_A:
		return MORTARK_KP_A;
	case SDLK_KP_B:
		return MORTARK_KP_B;
	case SDLK_KP_C:
		return MORTARK_KP_C;
	case SDLK_KP_D:
		return MORTARK_KP_D;
	case SDLK_KP_E:
		return MORTARK_KP_E;
	case SDLK_KP_F:
		return MORTARK_KP_F;
	case SDLK_KP_XOR:
		return MORTARK_KP_XOR;
	case SDLK_KP_POWER:
		return MORTARK_KP_POWER;
	case SDLK_KP_PERCENT:
		return MORTARK_KP_PERCENT;
	case SDLK_KP_LESS:
		return MORTARK_KP_LESS;
	case SDLK_KP_GREATER:
		return MORTARK_KP_GREATER;
	case SDLK_KP_AMPERSAND:
		return MORTARK_KP_AMPERSAND;
	case SDLK_KP_DBLAMPERSAND:
		return MORTARK_KP_DBLAMPERSAND;
	case SDLK_KP_VERTICALBAR:
		return MORTARK_KP_VERTICALBAR;
	case SDLK_KP_DBLVERTICALBAR:
		return MORTARK_KP_DBLVERTICALBAR;
	case SDLK_KP_COLON:
		return MORTARK_KP_COLON;
	case SDLK_KP_HASH:
		return MORTARK_KP_HASH;
	case SDLK_KP_SPACE:
		return MORTARK_KP_SPACE;
	case SDLK_KP_AT:
		return MORTARK_KP_AT;
	case SDLK_KP_EXCLAM:
		return MORTARK_KP_EXCLAM;
	case SDLK_KP_MEMSTORE:
		return MORTARK_KP_MEMSTORE;
	case SDLK_KP_MEMRECALL:
		return MORTARK_KP_MEMRECALL;
	case SDLK_KP_MEMCLEAR:
		return MORTARK_KP_MEMCLEAR;
	case SDLK_KP_MEMADD:
		return MORTARK_KP_MEMADD;
	case SDLK_KP_MEMSUBTRACT:
		return MORTARK_KP_MEMSUBTRACT;
	case SDLK_KP_MEMMULTIPLY:
		return MORTARK_KP_MEMMULTIPLY;
	case SDLK_KP_MEMDIVIDE:
		return MORTARK_KP_MEMDIVIDE;
	case SDLK_KP_PLUSMINUS:
		return MORTARK_KP_PLUSMINUS;
	case SDLK_KP_CLEAR:
		return MORTARK_KP_CLEAR;
	case SDLK_KP_CLEARENTRY:
		return MORTARK_KP_CLEARENTRY;
	case SDLK_KP_BINARY:
		return MORTARK_KP_BINARY;
	case SDLK_KP_OCTAL:
		return MORTARK_KP_OCTAL;
	case SDLK_KP_DECIMAL:
		return MORTARK_KP_DECIMAL;
	case SDLK_KP_HEXADECIMAL:
		return MORTARK_KP_HEXADECIMAL;
	case SDLK_LCTRL:
		return MORTARK_LCTRL;
	case SDLK_LSHIFT:
		return MORTARK_LSHIFT;
	case SDLK_LALT:
		return MORTARK_LALT;
	case SDLK_LGUI:
		return MORTARK_LGUI;
	case SDLK_RCTRL:
		return MORTARK_RCTRL;
	case SDLK_RSHIFT:
		return MORTARK_RSHIFT;
	case SDLK_RALT:
		return MORTARK_RALT;
	case SDLK_RGUI:
		return MORTARK_RGUI;
	case SDLK_MODE:
		return MORTARK_MODE;
	case SDLK_SLEEP:
		return MORTARK_SLEEP;
	case SDLK_WAKE:
		return MORTARK_WAKE;
	case SDLK_CHANNEL_INCREMENT:
		return MORTARK_CHANNEL_INCREMENT;
	case SDLK_CHANNEL_DECREMENT:
		return MORTARK_CHANNEL_DECREMENT;
	case SDLK_MEDIA_PLAY:
		return MORTARK_MEDIA_PLAY;
	case SDLK_MEDIA_PAUSE:
		return MORTARK_MEDIA_PAUSE;
	case SDLK_MEDIA_RECORD:
		return MORTARK_MEDIA_RECORD;
	case SDLK_MEDIA_FAST_FORWARD:
		return MORTARK_MEDIA_FAST_FORWARD;
	case SDLK_MEDIA_REWIND:
		return MORTARK_MEDIA_REWIND;
	case SDLK_MEDIA_NEXT_TRACK:
		return MORTARK_MEDIA_NEXT_TRACK;
	case SDLK_MEDIA_PREVIOUS_TRACK:
		return MORTARK_MEDIA_PREVIOUS_TRACK;
	case SDLK_MEDIA_STOP:
		return MORTARK_MEDIA_STOP;
	case SDLK_MEDIA_EJECT:
		return MORTARK_MEDIA_EJECT;
	case SDLK_MEDIA_PLAY_PAUSE:
		return MORTARK_MEDIA_PLAY_PAUSE;
	case SDLK_MEDIA_SELECT:
		return MORTARK_MEDIA_SELECT;
	case SDLK_AC_NEW:
		return MORTARK_AC_NEW;
	case SDLK_AC_OPEN:
		return MORTARK_AC_OPEN;
	case SDLK_AC_CLOSE:
		return MORTARK_AC_CLOSE;
	case SDLK_AC_EXIT:
		return MORTARK_AC_EXIT;
	case SDLK_AC_SAVE:
		return MORTARK_AC_SAVE;
	case SDLK_AC_PRINT:
		return MORTARK_AC_PRINT;
	case SDLK_AC_PROPERTIES:
		return MORTARK_AC_PROPERTIES;
	case SDLK_AC_SEARCH:
		return MORTARK_AC_SEARCH;
	case SDLK_AC_HOME:
		return MORTARK_AC_HOME;
	case SDLK_AC_BACK:
		return MORTARK_AC_BACK;
	case SDLK_AC_FORWARD:
		return MORTARK_AC_FORWARD;
	case SDLK_AC_STOP:
		return MORTARK_AC_STOP;
	case SDLK_AC_REFRESH:
		return MORTARK_AC_REFRESH;
	case SDLK_AC_BOOKMARKS:
		return MORTARK_AC_BOOKMARKS;
	case SDLK_SOFTLEFT:
		return MORTARK_SOFTLEFT;
	case SDLK_SOFTRIGHT:
		return MORTARK_SOFTRIGHT;
	case SDLK_CALL:
		return MORTARK_CALL;
	case SDLK_ENDCALL:
		return MORTARK_ENDCALL;
	case SDLK_LEFT_TAB:
		return MORTARK_LEFT_TAB;
	case SDLK_LEVEL5_SHIFT:
		return MORTARK_LEVEL5_SHIFT;
	case SDLK_MULTI_KEY_COMPOSE:
		return MORTARK_MULTI_KEY_COMPOSE;
	case SDLK_LMETA:
		return MORTARK_LMETA;
	case SDLK_RMETA:
		return MORTARK_RMETA;
	case SDLK_LHYPER:
		return MORTARK_LHYPER;
	case SDLK_RHYPER:
		return MORTARK_RHYPER;
	default:
		return keycode;
	}
}

SDL_Keymod keymod_mortar_to_sdl3(MORTAR_Keymod keymod)
{
	SDL_Keymod result = 0;
	if (keymod & MORTAR_KMOD_LSHIFT) {
		result |= SDL_KMOD_LSHIFT;
	}
	if (keymod & MORTAR_KMOD_RSHIFT) {
		result |= SDL_KMOD_RSHIFT;
	}
	if (keymod & MORTAR_KMOD_LEVEL5) {
		result |= SDL_KMOD_LEVEL5;
	}
	if (keymod & MORTAR_KMOD_LCTRL) {
		result |= SDL_KMOD_LCTRL;
	}
	if (keymod & MORTAR_KMOD_RCTRL) {
		result |= SDL_KMOD_RCTRL;
	}
	if (keymod & MORTAR_KMOD_LALT) {
		result |= SDL_KMOD_LALT;
	}
	if (keymod & MORTAR_KMOD_RALT) {
		result |= SDL_KMOD_RALT;
	}
	if (keymod & MORTAR_KMOD_LGUI) {
		result |= SDL_KMOD_LGUI;
	}
	if (keymod & MORTAR_KMOD_RGUI) {
		result |= SDL_KMOD_RGUI;
	}
	if (keymod & MORTAR_KMOD_NUM) {
		result |= SDL_KMOD_NUM;
	}
	if (keymod & MORTAR_KMOD_CAPS) {
		result |= SDL_KMOD_CAPS;
	}
	if (keymod & MORTAR_KMOD_MODE) {
		result |= SDL_KMOD_MODE;
	}
	if (keymod & MORTAR_KMOD_SCROLL) {
		result |= SDL_KMOD_SCROLL;
	}
	return result;
}

MORTAR_Keymod keymod_sdl3_to_mortar(SDL_Keymod keymod)
{
	MORTAR_Keymod result = 0;
	if (keymod & SDL_KMOD_LSHIFT) {
		result |= MORTAR_KMOD_LSHIFT;
	}
	if (keymod & SDL_KMOD_RSHIFT) {
		result |= MORTAR_KMOD_RSHIFT;
	}
	if (keymod & SDL_KMOD_LEVEL5) {
		result |= MORTAR_KMOD_LEVEL5;
	}
	if (keymod & SDL_KMOD_LCTRL) {
		result |= MORTAR_KMOD_LCTRL;
	}
	if (keymod & SDL_KMOD_RCTRL) {
		result |= MORTAR_KMOD_RCTRL;
	}
	if (keymod & SDL_KMOD_LALT) {
		result |= MORTAR_KMOD_LALT;
	}
	if (keymod & SDL_KMOD_RALT) {
		result |= MORTAR_KMOD_RALT;
	}
	if (keymod & SDL_KMOD_LGUI) {
		result |= MORTAR_KMOD_LGUI;
	}
	if (keymod & SDL_KMOD_RGUI) {
		result |= MORTAR_KMOD_RGUI;
	}
	if (keymod & SDL_KMOD_NUM) {
		result |= MORTAR_KMOD_NUM;
	}
	if (keymod & SDL_KMOD_CAPS) {
		result |= MORTAR_KMOD_CAPS;
	}
	if (keymod & SDL_KMOD_MODE) {
		result |= MORTAR_KMOD_MODE;
	}
	if (keymod & SDL_KMOD_SCROLL) {
		result |= MORTAR_KMOD_SCROLL;
	}
	return result;
}
