name: macOS

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja llvm
          echo "CLANG_TIDY=$(brew --prefix llvm)/bin/clang-tidy" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -S . -B build -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DISLE_USE_DX5=OFF \
            -DENABLE_CLANG_TIDY=ON \
            -DCLANG_TIDY_BIN=$CLANG_TIDY \
            -DISLE_WERROR=ON \
            -Werror=dev

      - name: Build
        run: cmake --build build -- -k0

      - name: Make Artifact Archive
        run: |
          cd build
          zip "isle-portable-macos-${{ matrix.build-type }}.zip" \
              config isle liblego1.dylib

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts-${{ matrix.build-type }}
          path: build/isle-portable-macos-${{ matrix.build-type }}.zip
