name: Windows

on: [push, pull_request]

jobs:
  build-current-toolchain:
    name: 'Current ${{ matrix.toolchain.name }}'
    runs-on: windows-latest
    defaults:
      run:
        shell: ${{ matrix.toolchain.shell }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - { name: 'MSVC (32-bit, Release)', shell: 'sh',  setup-cmake: true, setup-ninja: true, setup-msvc: true, vc-arch: 'amd64_x86',             dx5-libs: true,   d3drm-wrapper: false, build-type: 'Release' }
        - { name: 'MSVC (32-bit, Debug)',   shell: 'sh',  setup-cmake: true, setup-ninja: true, setup-msvc: true, vc-arch: 'amd64_x86',             dx5-libs: true,   d3drm-wrapper: false, build-type: 'Debug' }
        - { name: 'MSVC (64-bit, Debug)',   shell: 'sh',  setup-cmake: true, setup-ninja: true, setup-msvc: true, vc-arch: 'amd64',                 dx5-libs: false,  d3drm-wrapper: true,  build-type: 'Debug' }
        - { name: 'MSVC (ARM64, Debug)',    shell: 'sh',  setup-cmake: true, setup-ninja: true, setup-msvc: true, vc-arch: 'amd64_arm64',           dx5-libs: false,  d3drm-wrapper: true,  build-type: 'Debug' }
        - { name: 'msys2 mingw32 (Debug)',  shell: 'msys2 {0}', msystem: mingw32, msys-env: mingw-w64-i686,        clang-tidy: true, werror: true,  dx5-libs: false,  d3drm-wrapper: false, build-type: 'Debug' }
        - { name: 'msys2 mingw64 (Debug)',  shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64,      clang-tidy: true, werror: true,  dx5-libs: false,  d3drm-wrapper: false, build-type: 'Debug' }
        # - { name: 'msys2 clang32',  shell: 'msys2 {0}', msystem: clang32, msys-env: mingw-w64-clang-i686,  clang-tidy: true, werror: true, dx5-libs: true, d3drm-from-wine: true }

    steps:
      - name: Setup vcvars
        if: matrix.toolchain.setup-msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.toolchain.vc-arch }}
      # Figure out how to build for 32-bit arch
      # - name: Set up SDL
      #   id: sdl
      #   uses: libsdl-org/setup-sdl@main
      #   with:
      #     version: sdl3-head

      - name: Set up MSYS2
        if: ${{ !!matrix.toolchain.msystem }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.toolchain.msystem }}
          install: >-
            ${{ matrix.toolchain.msys-env }}-cc
            ${{ matrix.toolchain.msys-env }}-cmake
            ${{ matrix.toolchain.msys-env }}-ninja
            ${{ matrix.toolchain.msys-env }}-clang-tools-extra

      - name: Setup cmake
        if: matrix.toolchain.setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Setup ninja
        if: matrix.toolchain.setup-ninja
        uses: ashutoshvarma/setup-ninja@master

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        # Add -DDOWNLOAD_DEPENDENCIES=OFF once setup-sdl works
        run: |
          cmake -S . -B build -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.toolchain.build-type }} \
            -DISLE_USE_DX5=${{ matrix.toolchain.dx5-libs }} \
            -DISLE_D3DRM_WRAPPER=${{ matrix.toolchain.d3drm-wrapper }} \
            -DENABLE_CLANG_TIDY=${{ !!matrix.toolchain.clang-tidy }} \
            -DISLE_WERROR=${{ !!matrix.toolchain.werror }} \
            -Werror=dev
          cmake --build build -- -k0

      # Needs to be reworked when cross-platform building is achieved

      - name: Make Artifact Archive
        shell: bash
        run: |
          cd build
          7z a "isle-portable (${{ matrix.toolchain.name }}).zip" \
              isle.exe lego1.dll sdl3.dll

      - name: Upload Build Artifacts (MSVC (32-bit))
        if: ${{ matrix.toolchain.name == 'MSVC (32-bit, Release)' || matrix.toolchain.name == 'MSVC (32-bit, Debug)' }}
        uses: actions/upload-artifact@v4
        with:
          name: msvc32-artifacts-${{ matrix.toolchain.name }}
          path: |
            build/isle-portable (${{ matrix.toolchain.name }}).zip

  merge-artifacts:
    name: 'Merge artifacts'
    runs-on: ubuntu-latest
    needs: build-current-toolchain
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: msvc32-artifacts
          pattern: msvc32-artifacts-*

  upload:
    name: 'Upload artifacts'
    needs: merge-artifacts
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'isledecomp/isle-portable' }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'probonopd/uploadtool'

    - uses: actions/download-artifact@v4
      with:
        name: msvc32-artifacts
        path: build

    - name: Upload Continuous Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
      run: |
        ./upload.sh \
          build/*.zip
